/**
 * GitHub Actions cron-workflow generator for scheduled Veriflow flows.
 * Emits a ready-to-commit YAML that polls `veriflow schedules due --execute`
 * every 5 minutes (GitHub's cron is best-effort; the due-claim endpoint is
 * idempotent per minute so overlap is harmless), plus workflow_dispatch so
 * the schedule can be triggered by hand.
 */

export interface WorkflowOptions {
  name: string;
  /** 5-field cron, consumed verbatim by GitHub Actions' `schedule`. */
  schedule: string;
  /** Veriflow API base URL, e.g. https://api.acme.dev */
  apiUrl: string;
}

export function githubActionsWorkflow(opts: WorkflowOptions): string {
  // GitHub cron fields are space-separated; keep the user's expression as-is.
  const schedule = opts.schedule.trim();
  return `# Generated by Veriflow — schedules flow runs from GitHub Actions.
# Commit to .github/workflows/ and set VERIFLOW_API_KEY as a repo secret.
name: ${JSON.stringify(opts.name)}

on:
  schedule:
    - cron: ${JSON.stringify(schedule)}
  workflow_dispatch:

concurrency:
  group: veriflow-schedule
  cancel-in-progress: false

jobs:
  run-due-flows:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Veriflow CLI
        run: npm install -g @veriflow/cli || npm install -g ./packages/cli
      - name: Run due scheduled flows
        env:
          VERIFLOW_API_URL: ${JSON.stringify(opts.apiUrl)}
          VERIFLOW_API_KEY: \${{ secrets.VERIFLOW_API_KEY }}
        run: veriflow schedules due --execute --concurrency 4
`;
}
